### ISSUE TITLE
No error is returned from `trash::delete` if deleting file fails because the file or folder is opened by another process on windows

### ISSUE THREAD

**Issue by anatawa12** [Byron/trash-rs#104]
On windows, deleting file can be fail because another process is opening the file. (this is windows-specific behavior)

In such a case, this crate should return error but this crate returns without any error information.

Downstream issue: vrc-get/vrc-get#682

**Comment by Byron** [comment]
Thanks for reporting. 

I think it should be easily possible to reproduce this issue on Windows in a test, and then (possibly) fix it, assuming that this crate squelches an error that it should propagate.

**Comment by anatawa12** [comment]
https://github.com/Byron/trash-rs/blob/35b549f158428f0016a26c23249c76c6795ba9c3/src/windows.rs#L71-L71

I think second parameter of [`IFileOperationProgressSink::PostDeleteItem`] can be used but I'm not familiar with windows so I don't know this is true and safe to wait for it synchronously.
It looks implementation of `IFileOperationProgressSink` can be passed as second parameter of `DeleteItem`

[`IFileOperationProgressSink::PostDeleteItem]: https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifileoperationprogresssink-postdeleteitem
