### ISSUE TITLE
Expose documentation for DeleteMethod and other public APIs

### ISSUE THREAD

**Issue by eugenesvk** [Byron/trash-rs#121]
I've learned from the issues that on Mac your library supports the alternative non-Finder API, but couldn't find them in the published docs

Could you please expose everything in the docs? It's a bit strange given that, e.g., DeleteMethod, has valuable help message for its items, but that info is not visible...

**Comment by Byron** [comment]
PRs are definitely welcome.

Please note that platform specific documentation currently isn't done at all, but could be done with the right settings of `docs.rs` or maybe simply with platform specific sections in the current documentation.

**Comment by eugenesvk** [comment]
I couldn't find a great way around this: you can force-enable some items via `#cfg[doc]` to make it visible for rustdoc, but if you do it inside a platform-specific module, it still won't be shown, and the `platform` mod can't be force-enabled for the `doc` compliation target since it will then have duplicate conflicting names
And if you do some renaming, then doc fails to build due to missing os-specific dependencies, and there `[target.'cfg(doc)'.dependencies]` doesn't do anything as `doc` is not a valid target.

You could maybe move a few items outside its os-specific mod, but that's a bit backwards, think picking a different target at the docs.rs site is more appropriate despite being slightly inconvenient
