### ISSUE TITLE
Panic when deleting file with a non-UTF-8 name on a Mac

### ISSUE THREAD

**Issue by eugenesvk** [Byron/trash-rs#124]
Because it converts all paths to strings for some reason during the "canonicalization" step

https://github.com/Byron/trash-rs/blob/1a0fc5908a29c7e648a76ca706e2aa2a40eedda6/src/macos.rs#L65

**Comment by Byron** [comment]
Thanks a lot pointing this out!

It should definitely not be needed to do that, and I'd hope that a fix can be contributed.

**Comment by Byron** [comment]
> Upd: think it's just a matter of escaping binary chars to match the url format spec

I see, so applying a URL encoding to the bytes would do the trick? I wouldn't be surprised if NSURL is what's passed to the file-manager.

**Comment by eugenesvk** [comment]
It should, but the problem is I can't find an objc API for such a basic thing:

1. NSURL should get created from `fileURLWithPath(path: &NSString)`, so needs an NSString
    - there is a way to create it from bytes [URLWithDataRepresentation_relativeToURL](https://docs.rs/objc2-foundation/latest/objc2_foundation/struct.NSURL.html#method.URLWithDataRepresentation_relativeToURL), but it autoconverts bytes to their utf8 codes and escapes them and can't match the file name: for a file with a single `\xf8` (U+00F8 codepoint or utf8 0xC3 xB8 or `ø`) file name that in Finder is seen as `%F8` (so, %-byte-escaped), this api results in `%C3%B8` name, which is utf8
2. But then if we use NSString as input, which API allows to create an NSString from bytes with proper auto-escaping of invalid bytes?

I've even found another objc crate that has a method to get NSString from OsStr, but that one also failed with invalid utf8 [src](https://github.com/drewcrawford/foundationr/issues/1)

(yes, FM gets NSURL

https://github.com/Byron/trash-rs/blob/1a0fc5908a29c7e648a76ca706e2aa2a40eedda6/src/macos.rs#L80-L84

)

**Comment by eugenesvk** [comment]
@madsmtm you're the resident Objc guru that added objc2 crate. Would you please suggest how to do this simple thing:
- take an arbitrary bag of bytes file path (`OsStr` in Rust) and
- create an `NSUrl` in objc2 that can be fed to the FileManager for further processing?

**Comment by madsmtm** [comment]
Haven't researched closely yet, but what about [`-[NSURL fileURLWithFileSystemRepresentation:isDirectory:relativeToURL:]`](https://docs.rs/objc2-foundation/0.2.2/objc2_foundation/struct.NSURL.html#method.fileURLWithFileSystemRepresentation_isDirectory_relativeToURL)?

**Comment by madsmtm** [comment]
Where you'd get the pointer with [`OsStrExt`](https://doc.rust-lang.org/nightly/std/os/unix/ffi/trait.OsStrExt.html) to get the bytes + reallocating and adding a NUL byte to that with `CString`.

**Comment by eugenesvk** [comment]
That was the first one I've tried, also thought that the FS repr would mean raw bytes, but I get a panic

> unexpected NULL returned from -[NSFileManager stringWithFileSystemRepresentation:length:]

snippet I used for testing

```rs
let in_oss = OsStr::from_bytes(b"/Volumes/Untitled/\xf8");
let bpath = in_oss.as_bytes();
let cstring = CString::new(bpath).expect("CString::new failed to create from given path");
let cstring_len = cstring.count_bytes();
println!("cstring: {:?}={cstring_len}",cstring);
let nncstring = NonNull::new(cstring.into_raw()).expect("REASON");
println!("nncstring: {:?}",nncstring);
let string:Retained<NSString> = unsafe {file_mgr.stringWithFileSystemRepresentation_length(nncstring, cstring_len)};
```


this works with utf-8 `let in_oss = OsStr::from_bytes(b"/Volumes/Untitled/x");`, though, so I also assumed this was an encoding error. But maybe there is a simpler mistake?

**Comment by madsmtm** [comment]
No I mean `fileURLWithFileSystemRepresentation:isDirectory:relativeToURL:` on `NSURL`, not `stringWithFileSystemRepresentation:length:` on `NSFileManager`

**Comment by eugenesvk** [comment]
Sorry about the confusion, too many tests :)
Well, this one requires an unnecessary "is_dir" check, though might've also checked it before, but checked now as well, also can't find the file even though debug-prints the URL as `%F8` (in the correct version from valid utf8 it's `%25F8`, so `%` is escaped as well)

```rs
// URL from CString via fileURLWithFileSystemRepresentation_isDirectory_relativeToURL
  // FAILS with binary path
  let path_b:&[u8] = b"/Volumes/Untitled/\xf8";
  let path_os:&OsStr = OsStr::from_bytes(&path_b);
  let path_b:&[u8] = path_os.as_bytes();
  // OK with valid utf8 manual %-encoding
  let path_os:&OsStr = OsStr::new("/Volumes/Untitled/%F8");
  let path_b:&[u8] = path_os.as_bytes();

  // OK (different valid utf-8 string)
  let path_os:&OsStr = OsStr::new("/Volumes/Untitled/ピ");
  let path_b:&[u8] = path_os.as_bytes();


  // same in all cases
  let mut p:PathBuf = PathBuf::new(); p.push(path_os); let path_p = p;
  if path_p.is_file() {println!("path_os is a file! {:?}",path_os);}
  let cstring = CString::new(path_b).expect("CString::new failed to create from given path");
  let cstring_len = cstring.count_bytes();
  println!("pre={:?}\nc{}={:?}",&path_os,cstring_len,&cstring);
  let nncstring = NonNull::new(cstring.into_raw()).expect("REASON");
  let is_dir = false;
  let url_s = unsafe{NSURL::fileURLWithFileSystemRepresentation_isDirectory_relativeToURL(nncstring,is_dir,None)};
  // println!("fileURLWithFileSystemRepresentation_isDirectory_relativeToURL\n{url:?}",);

  let res_s = unsafe{file_mgr.trashItemAtURL_resultingItemURL_error(&url_s, None) };//
  let err_s = match res_s {Ok(())=>format!("ok"), Err(err)=>format!("{err}"),};
  println!("fileURLWithFileSystemRepresentation_isDirectory_relativeToURL:\nurl_s={url_s:?}\n\nres_s={err_s}");
```


I've meanwhile adapted the std's `from_utf8_lossy` function, but instead of replacing invalid utf8 byte sequences with a replacement char append them in a percent encoding, seems to work.
