### ISSUE TITLE
Build script doesn't work when cross compiling to Windows

### ISSUE THREAD

**Issue by Jake-Shadle** [Byron/trash-rs#39]
The build script doesn't generate bindings unless [running on Windows](https://github.com/ArturKovacs/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/build.rs#L4) which means compiling on a non-Windows platform targeting Windows won't generate the bindings and thus fail building as seen in https://github.com/Jake-Shadle/xwin/issues/10. The build script should use `CARGO_CFG_TARGET_OS` to determine whether it should build the bindings or not.

**Comment by ArturKovacs** [comment]
Hey, sorry for the slow response and thanks for the suggestion. I'm going to make the change, you suggested, but I'm afraid it still wouldn't work due to this: https://github.com/microsoft/windows-rs/issues/638. 

In the meantime consider using version 1 of this crate.

**Comment by ArturKovacs** [comment]
@Jake-Shadle I couldn't find a way to write to privately so I'm asking here: would you be interested in taking this crate over? I'd like to step away from maintaining it.

**Comment by Jake-Shadle** [comment]
Uhh sorry no, I only filed this issue due to https://github.com/Jake-Shadle/xwin/issues/10, I've never used this crate myself.

**Comment by ArturKovacs** [comment]
That's alright, thanks for the quick response anyways.

**Comment by ArturKovacs** [comment]
@Byron I can see that you are depending on this crate for `dua-cli`. Would you be interested in taking this crate over from me?

**Comment by Byron** [comment]
@ArturKovacs Thanks for asking, I am happy to take it over. I also hope you would still be available for occasional help on Windows (if issues come up) as I have decent access only to MacOS.

**Comment by ArturKovacs** [comment]
I'm wondering if we should transfer ownership to your account, @Byron

**Comment by Byron** [comment]
I am open to that, please feel free to initiate the transfer.

**Comment by qarmin** [comment]
Looks that this issue is already fixes in latest version of windows-rs, so only updating it from 0.9.0 version is required
https://github.com/Byron/trash-rs/blob/50ab31afa9f641a16a1ab50bf1ea8f8bacb0330f/Cargo.toml#L51-L54

**Comment by Byron** [comment]
If somebody wants to give #49 a shot…! I brought the `windows` crate upgrade down to 6 errors, and I think these can be fixed if somebody can figure out how to call these windows crate functions which changed their signatures quite significantly. Shouldn't be too hard, maybe @ArturKovacs could give it another try?

**Comment by Byron** [comment]
Please take a look at [the latest release](https://github.com/Byron/trash-rs/releases/tag/v2.1.4) for a fix to this problem. Since it uses no build script, there should be no related issues anymore.

Even though I am closing this issue in anticipation, please feel free to reopen if something else pops up.
