### ISSUE TITLE
Broken dependency resolution on non-Linux unixes

### ISSUE THREAD

**Issue by mqudsi** [Byron/trash-rs#40]
In `Cargo.toml`, `chrono` is declared as a dependency only under Linux:
https://github.com/Byron/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/Cargo.toml#L36-L37

But it is used in the Freedesktop backend without a Linux-only precondition:
https://github.com/Byron/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/src/freedesktop.rs#L18

And the Freedesktop backend is used for any non-macOS unix target:
https://github.com/Byron/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/src/lib.rs#L33-L35

This causes the build to fail when compiled on a non-Linux unix-ish platform like FreeBSD. 

The conditional dependency logic in Cargo.toml needs to match your actual use.

**Comment by ArturKovacs** [comment]
Feel free to ping me in January if I don't get back until then.

**Comment by Byron** [comment]
Thanks very much for reporting, and thanks @ArturKovacs for offering help, it's all very much appreciated.

To get a little more acquainted with the code-base I took a stab at it myself and [released a fix](https://github.com/Byron/trash-rs/releases/tag/v2.0.3).

Now the directives match so I'd hope this also fixes the related issue in `dua-cli`.

**Comment by ArturKovacs** [comment]
Thank you for taking good care of this repo @Byron ❤️

**Comment by mqudsi** [comment]
Thanks for the quick fix and I'm glad I could help. I was originally inclined to reported this as a dua bug because I use trash-rs in my own crates (thanks @ArturKovacs!) and haven't had issues compiling on FreeBSD but I just checked and it's because I opted into using trash 1.3 because of the guidance that was in the README at the time (details of which I cannot precisely recall at the moment).

Sorry to report that build still fails on non-Linux because of a different issue (unsafe use of Linux-only getmntent).

**Comment by Byron** [comment]
Step by step. If you could post the details here maybe a fix can be created from that.

It might also be useful to try and run CI on FreeBSD, [which doesn't seem to be straightforward yet](https://github.community/t/freebsd-support-for-ci-actions/200421).

So I guess we have to go step by step here, maybe it's easiest if @mqudsi would submit a PR that is proven to work.

**Comment by wezm** [comment]
> Sorry to report that build still fails on non-Linux because of a different issue (unsafe use of Linux-only getmntent).

Just ran into this issue on FreeBSD too.

> It might also be useful to try and run CI on FreeBSD, [which doesn't seem to be straightforward yet](https://github.community/t/freebsd-support-for-ci-actions/200421).

The easiest way to do CI for FreeBSD is with [Cirrus CI](https://cirrus-ci.org/). It's [free for open source](https://cirrus-ci.org/features/#free-for-open-source)
