### ISSUE TITLE
Failing test `platform::tests::test_list` when on system internal mounts

### ISSUE THREAD

**Issue by tenzap** [Byron/trash-rs#62]
when running `cargo test`, I have an error on this test: `platform::tests::test_list`

It is probably related to the path from where the command is executed.

```
running 8 tests
test tests::os_limited::purge_empty ... ok
test platform::tests::test_list ... FAILED
test tests::os_limited::purge ... ok
test tests::os_limited::restore_empty ... ok
test tests::os_limited::list ... ok
test tests::os_limited::restore ... ok
test tests::os_limited::restore_collision ... ok
test tests::os_limited::restore_twins ... ok

failures:

---- platform::tests::test_list stdout ----
thread 'platform::tests::test_list' panicked at 'called `Result::unwrap()` on an `Err` value: Other(Unknown { description: "Used 'gio', stderr: gio: file:///mnt/packages/git_repos/dpkg/debcargo-conf/build/trash/trash-test-1677542958831-0%230: Trashing on system internal mounts is not supported\ngio: file:///mnt/packages/git_repos/dpkg/debcargo-conf/build/trash/trash-test-1677542958831-0%231: Trashing on system internal mounts is not supported\ngio: file:///mnt/packages/git_repos/dpkg/debcargo-conf/build/trash/trash-test-1677542958831-0%232: Trashing on system internal mounts is not supported\n" })', src/freedesktop.rs:765:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by Byron** [comment]
Could you add information that helps to reproduce this? The OS and maybe the mountpoint in question might help - the error message suggests it's a mount special enough to make trashing impossible or require special precautions.

Thank you

**Comment by tenzap** [comment]
It's on Debian 
Mount point is /mnt/packages/git_repos
Nothing special about it afaik. ext4 fs.

**Comment by tenzap** [comment]
Actually, maybe it is because there is a bind mount in between. What about storing the tmp files in a system temporary dir like /tmp?

**Comment by Byron** [comment]
May I ask what happens if a file is trashed using the system 'explorer'-equivalent? Does it fail, too? If not, where does it put the trashed files?

**Comment by tenzap** [comment]
Do you know which command to run on the command line (no gui on the setup)

**Comment by tenzap** [comment]
If i run `gio trash file` I have the same error message.

**Comment by Byron** [comment]
Thanks a lot for your help This means it's an inherent limitation of the platform its running on and there is nothing one can reasonably do.

**Comment by ArturKovacs** [comment]
I'm pretty sure that you are not running the latest version of trash-rs. The latest version doesn't use gio.

**Comment by ArturKovacs** [comment]
Sorry what I wrote is not true. `gio` is in fact used for the list test linked below.

I agree with Byron in that if gio can't do this, and it only affects the test then the solution would probably be that you run the test in a folder where this issue doesn't surface.

https://github.com/Byron/trash-rs/blob/eef463aca73d5c623dd7b52bcb8b01b3b3d76b15/src/freedesktop.rs#L759

**Comment by tenzap** [comment]
I would still recommend to write to `env!("CARGO_TARGET_TMPDIR")` because since the tests are run automatically in my case, they are run from a dir where root access is required.

**Comment by Byron** [comment]
Thanks for the suggestion. Since you can easily reproduce this particular issue, would you be able to submit a PR with the fix?

**Comment by tenzap** [comment]
I don't know rust, i found this in other debian packages while trying to package yours. Sorry
