### ISSUE TITLE
Fails silently when `delete`ing a non-empty folder on Windows

### ISSUE THREAD

**Issue by bicarlsen** [Byron/trash-rs#70]
### Discussed in https://github.com/Byron/trash-rs/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **bicarlsen** May 22, 2023</sup>
On Windows, it seems the `delete` function does not delete a directory if it has contents, but will return `Ok`. Is this intended behavior? If so, would it be worth adding a `delete_recursive` convenience function so users don't have to manually walk the directory tree?</div>

**Comment by Byron** [comment]
Thanks for bringing this up. 

When looking at the documentation of [delete()](https://docs.rs/trash/3.0.2/trash/struct.TrashContext.html#method.delete) it's not entirely clear what should happen when a directory is encountered. It's likely that 'single' means 'empty' in case of a directory. This could be validated by looking at the tests, and then an improvement should be made to the docs to clarify.

Based on that outcome, a `delete_recursive()` function might be needed to handle this case more conveniently.

**Comment by bicarlsen** [comment]
I'm currently playing with a fix for this. I'll submit a PR once I get it sorted.

**Comment by bicarlsen** [comment]
A caveat is that the original function works if no files have content written in them (i.e. all files are 0 bytes).

**Comment by Byron** [comment]
This was fixed via #71 and released with [v3.0.5](https://github.com/Byron/trash-rs/releases/tag/v3.0.5).
