### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [Byron/trash-rs#86]
```rust
$ rustc -Vv
rustc 1.72.0 (5680fa18f 2023-08-23) (built from a source tarball)
binary: rustc
commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
commit-date: 2023-08-23
host: x86_64-unknown-freebsd
release: 1.72.0
LLVM version: 16.0.5

$ cargo build
[...]
error[E0308]: mismatched types
    --> src/freedesktop.rs:706:43
     |
706  |     let count = unsafe { libc::getmntinfo(&mut fs_infos, libc::MNT_WAIT) };
     |                          ---------------- ^^^^^^^^^^^^^ expected `*mut *mut statfs`, found `&mut *mut statvfs`
     |                          |
     |                          arguments to this function are incorrect
     |
     = note:    expected raw pointer `*mut *mut statfs`
             found mutable reference `&mut *mut statvfs`
note: function defined here
    --> cargo-crates/libc-0.2.149/src/unix/bsd/freebsdlike/freebsd/mod.rs:5222:12
     |
5222 |     pub fn getmntinfo(mntbufp: *mut *mut ::statfs, mode: ::c_int) -> ::c_int;
     |            ^^^^^^^^^^

error[E0609]: no field `f_mntfromname` on type `&statvfs`
   --> src/freedesktop.rs:714:20
    |
714 |         if fs_info.f_mntfromname[0] == 0 || fs_info.f_mntonname[0] == 0 {
    |                    ^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `f_bavail`, `f_bfree`, `f_blocks`, `f_favail`, `f_ffree` ... and 6 others

error[E0609]: no field `f_mntonname` on type `&statvfs`
   --> src/freedesktop.rs:714:53
    |
714 |         if fs_info.f_mntfromname[0] == 0 || fs_info.f_mntonname[0] == 0 {
    |                                                     ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `f_bavail`, `f_bfree`, `f_blocks`, `f_favail`, `f_ffree` ... and 6 others

error[E0609]: no field `f_fstypename` on type `&statvfs`
   --> src/freedesktop.rs:718:45
    |
718 |         let fs_type = c_buf_to_str(&fs_info.f_fstypename).unwrap_or_default();
    |                                             ^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `f_bavail`, `f_bfree`, `f_blocks`, `f_favail`, `f_ffree` ... and 6 others

error[E0609]: no field `f_mntonname` on type `&statvfs`
   --> src/freedesktop.rs:719:52
    |
719 |         let mount_to = match c_buf_to_str(&fs_info.f_mntonname) {
    |                                                    ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `f_bavail`, `f_bfree`, `f_blocks`, `f_favail`, `f_ffree` ... and 6 others

error[E0609]: no field `f_mntfromname` on type `&statvfs`
   --> src/freedesktop.rs:726:48
    |
726 |         let mount_from = c_buf_to_str(&fs_info.f_mntfromname).unwrap_or_default();
    |                                                ^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `f_bavail`, `f_bfree`, `f_blocks`, `f_favail`, `f_ffree` ... and 6 others

Some errors have detailed explanations: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
```

**Comment by Byron** [comment]
This shouldn't happen with the most recent version of `libc` which is enforced via manifest, so I don't know what's going on here.

The assumption here is that you are using the latest version which *seems* to be the case.

CC the author of this port @0323pin

**Comment by 0323pin** [comment]
@Byron I use NetBSD and not FreeBSD. So, I don't have a test environment to play with this.

Apparently, FreeBSD supports both the more recent [statvfs](https://man.freebsd.org/cgi/man.cgi?query=statvfs) and the older [statfs](https://man.freebsd.org/cgi/man.cgi?statfs(2)).

A quick look seems to indicate that these functions in `libc` are using statfs 😞

Two options here, either a PR on `libc` to make these function use statvfs instead of statfs or, conditioning my previous change here to NetBSD.

It's easy to test a FreeBSD specific patch for `libc` to see how that works, @jbeich are you willing to try that?

**Comment by 0323pin** [comment]
I should add that in NetBSD, statfs is not an option since,

> The statvfs(), statvfs1(), fstatvfs(), and fstatvfs1() functions first appeared in NetBSD 3.0 to replace the statfs() family of functions which first appeared in 4.4BSD

This is ages ago.

As for FreeBSD there's support for both, so why not switching to statvfs by default?

**Comment by jbeich** [comment]
> either a PR on `libc` to make these function use `statvfs` instead of `statfs`

How would this work? `libc` (Rust) crate imports a subset of `libc` (C) where FreeBSD [getmntinfo(3)](https://freebsd.org/getmntinfo/3) uses `statfs`. Switching to `statvfs` would break existing consumers and require `statfs` -> `statvfs` polyfill in a crate that is not supposed to abstract away OS differences.

**Comment by 0323pin** [comment]
@jbeich As mentioned, I don't use FreeBSD. I thought `statfs` existed only for backwards compatibility.

Although, these things should perhaps have been wrapped in a non-OS specific way, in this case the easiest way forward is probably to [split this](https://github.com/Byron/trash-rs/blob/master/src/freedesktop.rs#L681) into two different sections.  One for `target_os = netbsd` and another for `target_os = freebsd` and `target_os = openbsd`.

**Comment by 0323pin** [comment]
@jbeich Can you please run the following and confirm it builds on FreeBSD?

```
git clone https://github.com/0323pin/trash-rs
cd trash-rs
cargo build --release
```

Thanks!

**Comment by 0323pin** [comment]
@Byron I don't think we really need to wait for @jbeich to actually answer this. All I did was restore what was there previously for FreeBSD and the new section for NetBSD has been tested locally.

Unfortunately, `nushell` had a new release during this time. So just an [heads-up](https://github.com/nushell/nushell/blob/main/Cargo.lock#L5433) that building this new release on FreeBSD or, on OpenBSD will fail.

Sorry for the inconvenience. Please refer to this issue or, to the PR, if you hear complains.
Regards

**Comment by Byron** [comment]
A new release was made that should fix this issue: https://github.com/Byron/trash-rs/releases/tag/v3.1.1 .

**Comment by jbeich** [comment]
I confirm, v3.1.1 builds fine on FreeBSD.
